[workspace]
members = [
    "lib",
    "proto",
    "server",
    "client",
    "plugins/centrality",
    "plugins/hello_world",
    "plugins/host",
    "plugins/naive_vertex_count",
    "plugins/testing",
]